<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="$(SolutionDir)Settings/CommonSettings.xml" />
	<PropertyGroup>

		<Product>Goedel.Cryptography.Oauth</Product>
		<Description>Oauth2 support libraries.</Description>
		<Copyright>© 2024</Copyright>
		<Title>Goedel.Cryptography.Oauth</Title>

	</PropertyGroup>


	<ItemGroup>
		<ProjectReference Include="..\Goedel.Cryptography.Identifiers\Goedel.Cryptography.Identifiers.csproj" />
		<ProjectReference Include="..\Goedel.Cryptography.Nist\Goedel.Cryptography.Nist.csproj" />
		<ProjectReference Include="..\Goedel.Discovery\Goedel.Discovery.csproj" />
		<ProjectReference Include="..\Goedel.Protocol.Web\Goedel.Protocol.Web.csproj" />
		<ProjectReference Include="..\Goedel.Protocol\Goedel.Protocol.csproj" />
		<ProjectReference Include="..\Goedel.Utilities\Goedel.Utilities.csproj" />
	</ItemGroup>


	<ItemGroup>
	  <Compile Update="OauthSchema.cs">
		  <DependentUpon>OauthSchema.Protocol</DependentUpon>
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	  </Compile>
	  <Compile Update="OauthConstants.cs">
		  <DependentUpon>OauthConstants.constant</DependentUpon>
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	  </Compile>
	</ItemGroup>


	<ItemGroup>
	  <None Update="OauthSchema.Protocol">
	    <LastGenOutput>OauthSchema.cs</LastGenOutput>
	    <Generator>ProtoGen</Generator>
	  </None>
	  <None Update="OauthConstants.constant">
	    <LastGenOutput>OauthConstants.cs</LastGenOutput>
	    <Generator>Constant</Generator>
	  </None>
	</ItemGroup>



</Project>
