<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<Product>Goedel.Guigen</Product>
		<Description>Support library for GUI generator.</Description>
		<Title>Goedel.Guigen</Title>
		<Documents>false</Documents>
		<!--<UseMaui>true</UseMaui>-->
		<Copyright>© 2020-2025 Threshold Secrets LLC</Copyright>
		<OutputType>Library</OutputType>
		<BuildPlatform>All</BuildPlatform>
	</PropertyGroup>

	<Import Project="$(SolutionDir)Settings/MasterSettings.xml" />

	<ItemGroup>
		<ProjectReference Include="..\Goedel.Protocol\Goedel.Protocol.csproj" />
		<ProjectReference Include="..\Goedel.Utilities\Goedel.Utilities.csproj" />
	</ItemGroup>

</Project>
