<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<Product>Goedel.Cryptography.Test</Product>
		<Description>Cryptographic support libraries test modification</Description>
		<Title>Goedel.Cryptography.Test</Title>

		<Copyright>© 2020-2025 Threshold Secrets LLC</Copyright>
		<OutputType>Library</OutputType>
		<BuildPlatform>All</BuildPlatform>
	</PropertyGroup>

	<Import Project="$(SolutionDir)Settings/MasterSettings.xml" />
	<ItemGroup>
		<ProjectReference Include="..\Goedel.Cryptography.Dare\Goedel.Cryptography.Dare.csproj" />
		<ProjectReference Include="..\Goedel.Cryptography.Identifiers\Goedel.Cryptography.Identifiers.csproj" />
		<ProjectReference Include="..\Goedel.Cryptography\Goedel.Cryptography.csproj" />
	</ItemGroup>

</Project>
