//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Everything.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Sketch_resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Sketch_resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Everything.Resources.Sketch_resources", typeof(Sketch_resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Mesh Account.
        /// </summary>
        internal static string AccountCreate {
            get {
                return ResourceManager.GetString("AccountCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Account.
        /// </summary>
        internal static string AccountDelete {
            get {
                return ResourceManager.GetString("AccountDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create recovery.
        /// </summary>
        internal static string AccountGenerateRecovery {
            get {
                return ResourceManager.GetString("AccountGenerateRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create connection PIN.
        /// </summary>
        internal static string AccountGetPin {
            get {
                return ResourceManager.GetString("AccountGetPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account profile file is invalid.
        /// </summary>
        internal static string AccountProfileInvalid {
            get {
                return ResourceManager.GetString("AccountProfileInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover Mesh Account.
        /// </summary>
        internal static string AccountRecover {
            get {
                return ResourceManager.GetString("AccountRecover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect by Address.
        /// </summary>
        internal static string AccountRequestConnect {
            get {
                return ResourceManager.GetString("AccountRequestConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string AccountSection {
            get {
                return ResourceManager.GetString("AccountSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Account.
        /// </summary>
        internal static string AccountSwitch {
            get {
                return ResourceManager.GetString("AccountSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string AccountUser {
            get {
                return ResourceManager.GetString("AccountUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The activation key for the profile {0} could not be found.
        /// </summary>
        internal static string ActivationKeyNotFound {
            get {
                return ResourceManager.GetString("ActivationKeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Code Signing Key.
        /// </summary>
        internal static string AddCodeSigningKey {
            get {
                return ResourceManager.GetString("AddCodeSigningKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create git credentials.
        /// </summary>
        internal static string AddGitAccount {
            get {
                return ResourceManager.GetString("AddGitAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add email account.
        /// </summary>
        internal static string AddMailAccount {
            get {
                return ResourceManager.GetString("AddMailAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create SSH credential.
        /// </summary>
        internal static string AddSshAccount {
            get {
                return ResourceManager.GetString("AddSshAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows.
        /// </summary>
        internal static string Android {
            get {
                return ResourceManager.GetString("Android", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appartment.
        /// </summary>
        internal static string Appartment {
            get {
                return ResourceManager.GetString("Appartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        internal static string Appearance {
            get {
                return ResourceManager.GetString("Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applications.
        /// </summary>
        internal static string ApplicationSection {
            get {
                return ResourceManager.GetString("ApplicationSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Color.
        /// </summary>
        internal static string BackgroundColor {
            get {
                return ResourceManager.GetString("BackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmark.
        /// </summary>
        internal static string BookmarkSection {
            get {
                return ResourceManager.GetString("BookmarkSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string BoundAccount {
            get {
                return ResourceManager.GetString("BoundAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string BoundApplication {
            get {
                return ResourceManager.GetString("BoundApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string BoundApplicationCallSign {
            get {
                return ResourceManager.GetString("BoundApplicationCallSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string BoundApplicationDeveloper {
            get {
                return ResourceManager.GetString("BoundApplicationDeveloper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string BoundApplicationGroup {
            get {
                return ResourceManager.GetString("BoundApplicationGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string BoundApplicationMail {
            get {
                return ResourceManager.GetString("BoundApplicationMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string BoundApplicationOpenPgp {
            get {
                return ResourceManager.GetString("BoundApplicationOpenPgp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string BoundApplicationPkix {
            get {
                return ResourceManager.GetString("BoundApplicationPkix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string BoundApplicationSsh {
            get {
                return ResourceManager.GetString("BoundApplicationSsh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment.
        /// </summary>
        internal static string BoundAppointment {
            get {
                return ResourceManager.GetString("BoundAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmark.
        /// </summary>
        internal static string BoundBookmark {
            get {
                return ResourceManager.GetString("BoundBookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization.
        /// </summary>
        internal static string BoundContactBusiness {
            get {
                return ResourceManager.GetString("BoundContactBusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person.
        /// </summary>
        internal static string BoundContactPerson {
            get {
                return ResourceManager.GetString("BoundContactPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place.
        /// </summary>
        internal static string BoundContactPlace {
            get {
                return ResourceManager.GetString("BoundContactPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passkey.
        /// </summary>
        internal static string BoundCredential {
            get {
                return ResourceManager.GetString("BoundCredential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string BoundDevice {
            get {
                return ResourceManager.GetString("BoundDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        internal static string BoundDocument {
            get {
                return ResourceManager.GetString("BoundDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feed.
        /// </summary>
        internal static string BoundFeed {
            get {
                return ResourceManager.GetString("BoundFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        internal static string BoundGroup {
            get {
                return ResourceManager.GetString("BoundGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail.
        /// </summary>
        internal static string BoundMailMail {
            get {
                return ResourceManager.GetString("BoundMailMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string BoundMessage {
            get {
                return ResourceManager.GetString("BoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail.
        /// </summary>
        internal static string BoundMessageConfirmationRequest {
            get {
                return ResourceManager.GetString("BoundMessageConfirmationRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail.
        /// </summary>
        internal static string BoundMessageConfirmationResponse {
            get {
                return ResourceManager.GetString("BoundMessageConfirmationResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail.
        /// </summary>
        internal static string BoundMessageConnectionRequest {
            get {
                return ResourceManager.GetString("BoundMessageConnectionRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail.
        /// </summary>
        internal static string BoundMessageContactRequest {
            get {
                return ResourceManager.GetString("BoundMessageContactRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail.
        /// </summary>
        internal static string BoundMessageGroupInvitation {
            get {
                return ResourceManager.GetString("BoundMessageGroupInvitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail.
        /// </summary>
        internal static string BoundMessageTaskRequest {
            get {
                return ResourceManager.GetString("BoundMessageTaskRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passkey.
        /// </summary>
        internal static string BoundPasskey {
            get {
                return ResourceManager.GetString("BoundPasskey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string BoundPassword {
            get {
                return ResourceManager.GetString("BoundPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task.
        /// </summary>
        internal static string BoundTask {
            get {
                return ResourceManager.GetString("BoundTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        internal static string CalendarSection {
            get {
                return ResourceManager.GetString("CalendarSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalog.
        /// </summary>
        internal static string CatalogName {
            get {
                return ResourceManager.GetString("CatalogName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applications.
        /// </summary>
        internal static string ChooseApplication {
            get {
                return ResourceManager.GetString("ChooseApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        internal static string ChooseAppointment {
            get {
                return ResourceManager.GetString("ChooseAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmark.
        /// </summary>
        internal static string ChooseBookmark {
            get {
                return ResourceManager.GetString("ChooseBookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        internal static string ChooseContact {
            get {
                return ResourceManager.GetString("ChooseContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credentials.
        /// </summary>
        internal static string ChooseCredential {
            get {
                return ResourceManager.GetString("ChooseCredential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices.
        /// </summary>
        internal static string ChooseDevice {
            get {
                return ResourceManager.GetString("ChooseDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        internal static string ChooseDocuments {
            get {
                return ResourceManager.GetString("ChooseDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feeds.
        /// </summary>
        internal static string ChooseFeed {
            get {
                return ResourceManager.GetString("ChooseFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string ChooseGroup {
            get {
                return ResourceManager.GetString("ChooseGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        internal static string ChooseMessage {
            get {
                return ResourceManager.GetString("ChooseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        internal static string ChooseService {
            get {
                return ResourceManager.GetString("ChooseService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        internal static string ChooseTask {
            get {
                return ResourceManager.GetString("ChooseTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string ChooseUser {
            get {
                return ResourceManager.GetString("ChooseUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        internal static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respond.
        /// </summary>
        internal static string ConfirmationAccept {
            get {
                return ResourceManager.GetString("ConfirmationAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respond.
        /// </summary>
        internal static string ConfirmationReject {
            get {
                return ResourceManager.GetString("ConfirmationReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation code (if provided).
        /// </summary>
        internal static string ConnectionPin {
            get {
                return ResourceManager.GetString("ConnectionPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account address.
        /// </summary>
        internal static string ConnectionString {
            get {
                return ResourceManager.GetString("ConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network.
        /// </summary>
        internal static string ContactNetworkAddress {
            get {
                return ResourceManager.GetString("ContactNetworkAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place.
        /// </summary>
        internal static string ContactPhysicalAddress {
            get {
                return ResourceManager.GetString("ContactPhysicalAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        internal static string ContactSection {
            get {
                return ResourceManager.GetString("ContactSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string ContentType {
            get {
                return ResourceManager.GetString("ContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request requires counterparty confirmation.
        /// </summary>
        internal static string CounterpartyApproval {
            get {
                return ResourceManager.GetString("CounterpartyApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to County.
        /// </summary>
        internal static string County {
            get {
                return ResourceManager.GetString("County", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation code (if provided).
        /// </summary>
        internal static string Coupon {
            get {
                return ResourceManager.GetString("Coupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Chat.
        /// </summary>
        internal static string CreateChat {
            get {
                return ResourceManager.GetString("CreateChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Mail.
        /// </summary>
        internal static string CreateMail {
            get {
                return ResourceManager.GetString("CreateMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The host refused service on account of an invalid credential.
        /// </summary>
        internal static string CredentialRefused {
            get {
                return ResourceManager.GetString("CredentialRefused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credentials.
        /// </summary>
        internal static string CredentialSection {
            get {
                return ResourceManager.GetString("CredentialSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Present QR.
        /// </summary>
        internal static string DeviceConnectQR {
            get {
                return ResourceManager.GetString("DeviceConnectQR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device profile file is invalid.
        /// </summary>
        internal static string DeviceProfileInvalid {
            get {
                return ResourceManager.GetString("DeviceProfileInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This device is no longer authorized to access this account.
        /// </summary>
        internal static string DeviceRefused {
            get {
                return ResourceManager.GetString("DeviceRefused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices.
        /// </summary>
        internal static string DeviceSection {
            get {
                return ResourceManager.GetString("DeviceSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name.
        /// </summary>
        internal static string Display {
            get {
                return ResourceManager.GetString("Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District.
        /// </summary>
        internal static string District {
            get {
                return ResourceManager.GetString("District", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        internal static string DocumentSection {
            get {
                return ResourceManager.GetString("DocumentSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel.
        /// </summary>
        internal static string Excel {
            get {
                return ResourceManager.GetString("Excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiry in hours.
        /// </summary>
        internal static string Expire {
            get {
                return ResourceManager.GetString("Expire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messenger.
        /// </summary>
        internal static string Facebook {
            get {
                return ResourceManager.GetString("Facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facetime.
        /// </summary>
        internal static string Facetime {
            get {
                return ResourceManager.GetString("Facetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feeds.
        /// </summary>
        internal static string FeedSection {
            get {
                return ResourceManager.GetString("FeedSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name.
        /// </summary>
        internal static string Filename {
            get {
                return ResourceManager.GetString("Filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read file {0}.
        /// </summary>
        internal static string FileReadError {
            get {
                return ResourceManager.GetString("FileReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not write file {0}.
        /// </summary>
        internal static string FileWriteError {
            get {
                return ResourceManager.GetString("FileWriteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fingerprint.
        /// </summary>
        internal static string Fingerprint {
            get {
                return ResourceManager.GetString("Fingerprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        internal static string First {
            get {
                return ResourceManager.GetString("First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub.
        /// </summary>
        internal static string GitHub {
            get {
                return ResourceManager.GetString("GitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        internal static string GroupSection {
            get {
                return ResourceManager.GetString("GroupSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight Color.
        /// </summary>
        internal static string HighlightColor {
            get {
                return ResourceManager.GetString("HighlightColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No host could not be reached for service {0}.
        /// </summary>
        internal static string HostNotFound {
            get {
                return ResourceManager.GetString("HostNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host fingerprint.
        /// </summary>
        internal static string HostUdf {
            get {
                return ResourceManager.GetString("HostUdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Mesh service did not respond.
        /// </summary>
        internal static string HttpRequestFail {
            get {
                return ResourceManager.GetString("HttpRequestFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon Size.
        /// </summary>
        internal static string IconSize {
            get {
                return ResourceManager.GetString("IconSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        internal static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The host presented an invalid credential.
        /// </summary>
        internal static string InvalidHostCredential {
            get {
                return ResourceManager.GetString("InvalidHostCredential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows.
        /// </summary>
        internal static string IOS {
            get {
                return ResourceManager.GetString("IOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        internal static string Last {
            get {
                return ResourceManager.GetString("Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        internal static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LinkedIn.
        /// </summary>
        internal static string LinkedIn {
            get {
                return ResourceManager.GetString("LinkedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must specify a URI.
        /// </summary>
        internal static string LinkIsNull {
            get {
                return ResourceManager.GetString("LinkIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows.
        /// </summary>
        internal static string Linux {
            get {
                return ResourceManager.GetString("Linux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friendly name.
        /// </summary>
        internal static string Local {
            get {
                return ResourceManager.GetString("Local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Address.
        /// </summary>
        internal static string LocalAddress {
            get {
                return ResourceManager.GetString("LocalAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locality.
        /// </summary>
        internal static string Locality {
            get {
                return ResourceManager.GetString("Locality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local.
        /// </summary>
        internal static string LocalName {
            get {
                return ResourceManager.GetString("LocalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        internal static string Longitude {
            get {
                return ResourceManager.GetString("Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows.
        /// </summary>
        internal static string MacOs {
            get {
                return ResourceManager.GetString("MacOs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        internal static string Medium {
            get {
                return ResourceManager.GetString("Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        internal static string MessageSection {
            get {
                return ResourceManager.GetString("MessageSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Addresses.
        /// </summary>
        internal static string NetworkAddress {
            get {
                return ResourceManager.GetString("NetworkAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This device is not authorized to perform administrative requests.
        /// </summary>
        internal static string NotAuthorizedAdministration {
            get {
                return ResourceManager.GetString("NotAuthorizedAdministration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This device is not authorized to access the {0} catalog.
        /// </summary>
        internal static string NotAuthorizedCatalog {
            get {
                return ResourceManager.GetString("NotAuthorizedCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This device is not authorized to access the {0} catalog.
        /// </summary>
        internal static string NotAuthorizedFCatalog {
            get {
                return ResourceManager.GetString("NotAuthorizedFCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feature is not yet implemented.
        /// </summary>
        internal static string NotYetImplemented {
            get {
                return ResourceManager.GetString("NotYetImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total number of shares.
        /// </summary>
        internal static string NumberShares {
            get {
                return ResourceManager.GetString("NumberShares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be an integer 1-15.
        /// </summary>
        internal static string NumberSharesRange {
            get {
                return ResourceManager.GetString("NumberSharesRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF.
        /// </summary>
        internal static string PDF {
            get {
                return ResourceManager.GetString("PDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locations.
        /// </summary>
        internal static string PhysicalAddress {
            get {
                return ResourceManager.GetString("PhysicalAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postcode.
        /// </summary>
        internal static string Postcode {
            get {
                return ResourceManager.GetString("Postcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PowerPoint.
        /// </summary>
        internal static string PowerPoint {
            get {
                return ResourceManager.GetString("PowerPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefix.
        /// </summary>
        internal static string Prefix {
            get {
                return ResourceManager.GetString("Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile fingerprint.
        /// </summary>
        internal static string ProfileUdf {
            get {
                return ResourceManager.GetString("ProfileUdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protocol.
        /// </summary>
        internal static string Protocol {
            get {
                return ResourceManager.GetString("Protocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact QR.
        /// </summary>
        internal static string QrCode {
            get {
                return ResourceManager.GetString("QrCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect by QR.
        /// </summary>
        internal static string QrContact {
            get {
                return ResourceManager.GetString("QrContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quorum required for recovery.
        /// </summary>
        internal static string Quorum {
            get {
                return ResourceManager.GetString("Quorum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RasberryPi.
        /// </summary>
        internal static string RasberryPi {
            get {
                return ResourceManager.GetString("RasberryPi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Recipient {
            get {
                return ResourceManager.GetString("Recipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation Request.
        /// </summary>
        internal static string RequestConfirmation {
            get {
                return ResourceManager.GetString("RequestConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Contact.
        /// </summary>
        internal static string RequestContact {
            get {
                return ResourceManager.GetString("RequestContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request.
        /// </summary>
        internal static string RequestMessage {
            get {
                return ResourceManager.GetString("RequestMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested rights.
        /// </summary>
        internal static string Rights {
            get {
                return ResourceManager.GetString("Rights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security level.
        /// </summary>
        internal static string Security {
            get {
                return ResourceManager.GetString("Security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be an integer 0-5.
        /// </summary>
        internal static string SecurityRange {
            get {
                return ResourceManager.GetString("SecurityRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send document.
        /// </summary>
        internal static string SendDocument {
            get {
                return ResourceManager.GetString("SendDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender.
        /// </summary>
        internal static string Sender {
            get {
                return ResourceManager.GetString("Sender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        internal static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Address.
        /// </summary>
        internal static string ServiceAddress {
            get {
                return ResourceManager.GetString("ServiceAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service address cannot be blank.
        /// </summary>
        internal static string ServiceAddressNotEmpty {
            get {
                return ResourceManager.GetString("ServiceAddressNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a valid service address.
        /// </summary>
        internal static string ServiceAddressNotValid {
            get {
                return ResourceManager.GetString("ServiceAddressNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Callsign.
        /// </summary>
        internal static string ServiceCallsign {
            get {
                return ResourceManager.GetString("ServiceCallsign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DNS.
        /// </summary>
        internal static string ServiceDns {
            get {
                return ResourceManager.GetString("ServiceDns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string ServiceMessage {
            get {
                return ResourceManager.GetString("ServiceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service {0} could not be found.
        /// </summary>
        internal static string ServiceNotFound {
            get {
                return ResourceManager.GetString("ServiceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service refused the request.
        /// </summary>
        internal static string ServiceRefused {
            get {
                return ResourceManager.GetString("ServiceRefused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        internal static string ServiceSection {
            get {
                return ResourceManager.GetString("ServiceSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service fingerprint.
        /// </summary>
        internal static string ServiceUdf {
            get {
                return ResourceManager.GetString("ServiceUdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingSection {
            get {
                return ResourceManager.GetString("SettingSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery share.
        /// </summary>
        internal static string Share1 {
            get {
                return ResourceManager.GetString("Share1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery share.
        /// </summary>
        internal static string Share2 {
            get {
                return ResourceManager.GetString("Share2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery share.
        /// </summary>
        internal static string Share3 {
            get {
                return ResourceManager.GetString("Share3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery share.
        /// </summary>
        internal static string Share4 {
            get {
                return ResourceManager.GetString("Share4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery share.
        /// </summary>
        internal static string Share5 {
            get {
                return ResourceManager.GetString("Share5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery share.
        /// </summary>
        internal static string Share6 {
            get {
                return ResourceManager.GetString("Share6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery share.
        /// </summary>
        internal static string Share7 {
            get {
                return ResourceManager.GetString("Share7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery share.
        /// </summary>
        internal static string Share8 {
            get {
                return ResourceManager.GetString("Share8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share document.
        /// </summary>
        internal static string ShareDocument {
            get {
                return ResourceManager.GetString("ShareDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signal.
        /// </summary>
        internal static string Signal {
            get {
                return ResourceManager.GetString("Signal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skype.
        /// </summary>
        internal static string Skype {
            get {
                return ResourceManager.GetString("Skype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Video.
        /// </summary>
        internal static string StartVideo {
            get {
                return ResourceManager.GetString("StartVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Voice.
        /// </summary>
        internal static string StartVoice {
            get {
                return ResourceManager.GetString("StartVoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        internal static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        internal static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suffix.
        /// </summary>
        internal static string Suffix {
            get {
                return ResourceManager.GetString("Suffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application failure.
        /// </summary>
        internal static string SystemExeption {
            get {
                return ResourceManager.GetString("SystemExeption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        internal static string TaskSection {
            get {
                return ResourceManager.GetString("TaskSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telegram.
        /// </summary>
        internal static string Telegram {
            get {
                return ResourceManager.GetString("Telegram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string Telephone {
            get {
                return ResourceManager.GetString("Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Service.
        /// </summary>
        internal static string TestService {
            get {
                return ResourceManager.GetString("TestService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Color.
        /// </summary>
        internal static string TextColor {
            get {
                return ResourceManager.GetString("TextColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Size.
        /// </summary>
        internal static string TextSize {
            get {
                return ResourceManager.GetString("TextSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent.
        /// </summary>
        internal static string TimeSent {
            get {
                return ResourceManager.GetString("TimeSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter.
        /// </summary>
        internal static string Twitter {
            get {
                return ResourceManager.GetString("Twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Udf.
        /// </summary>
        internal static string Udf {
            get {
                return ResourceManager.GetString("Udf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        internal static string Uri {
            get {
                return ResourceManager.GetString("Uri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices.
        /// </summary>
        internal static string UserChooseDevice {
            get {
                return ResourceManager.GetString("UserChooseDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whatsapp.
        /// </summary>
        internal static string Whatsapp {
            get {
                return ResourceManager.GetString("Whatsapp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows.
        /// </summary>
        internal static string Windows {
            get {
                return ResourceManager.GetString("Windows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word.
        /// </summary>
        internal static string Word {
            get {
                return ResourceManager.GetString("Word", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wordpress.
        /// </summary>
        internal static string Wordpress {
            get {
                return ResourceManager.GetString("Wordpress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip.
        /// </summary>
        internal static string Zip {
            get {
                return ResourceManager.GetString("Zip", resourceCulture);
            }
        }
    }
}
