//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Everything.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Sketch_resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Sketch_resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = 
                        new global::System.Resources.ResourceManager("Everything.Resources.Sketch_resources", typeof(Sketch_resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect To Existing Account.
        /// </summary>
        internal static string AccountConnect {
            get {
                return ResourceManager.GetString("AccountConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Mesh Account.
        /// </summary>
        internal static string AccountCreate {
            get {
                return ResourceManager.GetString("AccountCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover Mesh Account.
        /// </summary>
        internal static string AccountRecover {
            get {
                return ResourceManager.GetString("AccountRecover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Account.
        /// </summary>
        internal static string AccountSwitch {
            get {
                return ResourceManager.GetString("AccountSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appartment.
        /// </summary>
        internal static string Appartment {
            get {
                return ResourceManager.GetString("Appartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applications.
        /// </summary>
        internal static string Applications {
            get {
                return ResourceManager.GetString("Applications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Color.
        /// </summary>
        internal static string BackgroundColor {
            get {
                return ResourceManager.GetString("BackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body.
        /// </summary>
        internal static string Body {
            get {
                return ResourceManager.GetString("Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmark.
        /// </summary>
        internal static string Bookmark {
            get {
                return ResourceManager.GetString("Bookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        internal static string Calendar {
            get {
                return ResourceManager.GetString("Calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applications.
        /// </summary>
        internal static string ChooseApplication {
            get {
                return ResourceManager.GetString("ChooseApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        internal static string ChooseAppointment {
            get {
                return ResourceManager.GetString("ChooseAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmark.
        /// </summary>
        internal static string ChooseBookmark {
            get {
                return ResourceManager.GetString("ChooseBookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        internal static string ChooseContact {
            get {
                return ResourceManager.GetString("ChooseContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credentials.
        /// </summary>
        internal static string ChooseCredential {
            get {
                return ResourceManager.GetString("ChooseCredential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices.
        /// </summary>
        internal static string ChooseDevice {
            get {
                return ResourceManager.GetString("ChooseDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        internal static string ChooseDocuments {
            get {
                return ResourceManager.GetString("ChooseDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feeds.
        /// </summary>
        internal static string ChooseFeed {
            get {
                return ResourceManager.GetString("ChooseFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string ChooseGroup {
            get {
                return ResourceManager.GetString("ChooseGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        internal static string ChooseMessage {
            get {
                return ResourceManager.GetString("ChooseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        internal static string ChooseService {
            get {
                return ResourceManager.GetString("ChooseService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        internal static string ChooseTask {
            get {
                return ResourceManager.GetString("ChooseTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string ChooseUser {
            get {
                return ResourceManager.GetString("ChooseUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation code (if provided).
        /// </summary>
        internal static string ConnectionPin {
            get {
                return ResourceManager.GetString("ConnectionPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account address.
        /// </summary>
        internal static string ConnectionString {
            get {
                return ResourceManager.GetString("ConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        internal static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string ContentType {
            get {
                return ResourceManager.GetString("ContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to County.
        /// </summary>
        internal static string County {
            get {
                return ResourceManager.GetString("County", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation code (if provided).
        /// </summary>
        internal static string Coupon {
            get {
                return ResourceManager.GetString("Coupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Chat.
        /// </summary>
        internal static string CreateChat {
            get {
                return ResourceManager.GetString("CreateChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Mail.
        /// </summary>
        internal static string CreateMail {
            get {
                return ResourceManager.GetString("CreateMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credentials.
        /// </summary>
        internal static string Credentials {
            get {
                return ResourceManager.GetString("Credentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices.
        /// </summary>
        internal static string Devices {
            get {
                return ResourceManager.GetString("Devices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District.
        /// </summary>
        internal static string District {
            get {
                return ResourceManager.GetString("District", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        internal static string Documents {
            get {
                return ResourceManager.GetString("Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feeds.
        /// </summary>
        internal static string Feeds {
            get {
                return ResourceManager.GetString("Feeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fingerprint.
        /// </summary>
        internal static string Fingerprint {
            get {
                return ResourceManager.GetString("Fingerprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        internal static string First {
            get {
                return ResourceManager.GetString("First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name.
        /// </summary>
        internal static string Full {
            get {
                return ResourceManager.GetString("Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        internal static string Groups {
            get {
                return ResourceManager.GetString("Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight Color.
        /// </summary>
        internal static string HighlightColor {
            get {
                return ResourceManager.GetString("HighlightColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host fingerprint.
        /// </summary>
        internal static string HostUdf {
            get {
                return ResourceManager.GetString("HostUdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon Size.
        /// </summary>
        internal static string IconSize {
            get {
                return ResourceManager.GetString("IconSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        internal static string Last {
            get {
                return ResourceManager.GetString("Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        internal static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friendly name.
        /// </summary>
        internal static string Local {
            get {
                return ResourceManager.GetString("Local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Address.
        /// </summary>
        internal static string LocalAddress {
            get {
                return ResourceManager.GetString("LocalAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locality.
        /// </summary>
        internal static string Locality {
            get {
                return ResourceManager.GetString("Locality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friendly name (optional).
        /// </summary>
        internal static string LocalName {
            get {
                return ResourceManager.GetString("LocalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        internal static string Longitude {
            get {
                return ResourceManager.GetString("Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        internal static string Messages {
            get {
                return ResourceManager.GetString("Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Addresses.
        /// </summary>
        internal static string NetworkAddress {
            get {
                return ResourceManager.GetString("NetworkAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locations.
        /// </summary>
        internal static string PhysicalAddress {
            get {
                return ResourceManager.GetString("PhysicalAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postcode.
        /// </summary>
        internal static string Postcode {
            get {
                return ResourceManager.GetString("Postcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefix.
        /// </summary>
        internal static string Prefix {
            get {
                return ResourceManager.GetString("Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile fingerprint.
        /// </summary>
        internal static string ProfileUdf {
            get {
                return ResourceManager.GetString("ProfileUdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protocol.
        /// </summary>
        internal static string Protocol {
            get {
                return ResourceManager.GetString("Protocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to protocol_icon.
        /// </summary>
        internal static string ProtocolIcon {
            get {
                return ResourceManager.GetString("ProtocolIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request.
        /// </summary>
        internal static string Request {
            get {
                return ResourceManager.GetString("Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Request.
        /// </summary>
        internal static string RequestContact {
            get {
                return ResourceManager.GetString("RequestContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send document.
        /// </summary>
        internal static string SendDocument {
            get {
                return ResourceManager.GetString("SendDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site.
        /// </summary>
        internal static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Address.
        /// </summary>
        internal static string ServiceAddress {
            get {
                return ResourceManager.GetString("ServiceAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service address cannot be blank.
        /// </summary>
        internal static string ServiceAddressNotEmpty {
            get {
                return ResourceManager.GetString("ServiceAddressNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a valid service address.
        /// </summary>
        internal static string ServiceAddressNotValid {
            get {
                return ResourceManager.GetString("ServiceAddressNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Callsign.
        /// </summary>
        internal static string ServiceCallsign {
            get {
                return ResourceManager.GetString("ServiceCallsign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DNS.
        /// </summary>
        internal static string ServiceDns {
            get {
                return ResourceManager.GetString("ServiceDns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        internal static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service fingerprint.
        /// </summary>
        internal static string ServiceUdf {
            get {
                return ResourceManager.GetString("ServiceUdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery share.
        /// </summary>
        internal static string Share1 {
            get {
                return ResourceManager.GetString("Share1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery share.
        /// </summary>
        internal static string Share2 {
            get {
                return ResourceManager.GetString("Share2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery share.
        /// </summary>
        internal static string Share3 {
            get {
                return ResourceManager.GetString("Share3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery share.
        /// </summary>
        internal static string Share4 {
            get {
                return ResourceManager.GetString("Share4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery share.
        /// </summary>
        internal static string Share5 {
            get {
                return ResourceManager.GetString("Share5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery share.
        /// </summary>
        internal static string Share6 {
            get {
                return ResourceManager.GetString("Share6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery share.
        /// </summary>
        internal static string Share7 {
            get {
                return ResourceManager.GetString("Share7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery share.
        /// </summary>
        internal static string Share8 {
            get {
                return ResourceManager.GetString("Share8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share document.
        /// </summary>
        internal static string ShareDocument {
            get {
                return ResourceManager.GetString("ShareDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Video.
        /// </summary>
        internal static string StartVideo {
            get {
                return ResourceManager.GetString("StartVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Voice.
        /// </summary>
        internal static string StartVoice {
            get {
                return ResourceManager.GetString("StartVoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        internal static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        internal static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suffix.
        /// </summary>
        internal static string Suffix {
            get {
                return ResourceManager.GetString("Suffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        internal static string Tasks {
            get {
                return ResourceManager.GetString("Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Service.
        /// </summary>
        internal static string TestService {
            get {
                return ResourceManager.GetString("TestService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Color.
        /// </summary>
        internal static string TextColor {
            get {
                return ResourceManager.GetString("TextColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Size.
        /// </summary>
        internal static string TextSize {
            get {
                return ResourceManager.GetString("TextSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fingerprint.
        /// </summary>
        internal static string Udf {
            get {
                return ResourceManager.GetString("Udf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uri.
        /// </summary>
        internal static string Uri {
            get {
                return ResourceManager.GetString("Uri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices.
        /// </summary>
        internal static string UserChooseDevice {
            get {
                return ResourceManager.GetString("UserChooseDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
    }
}
