<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<AssemblyName>serviceadmin</AssemblyName>
		<Product>serviceadmin</Product>
		<Description>Mesh service host.</Description>
		<Copyright>© 2021</Copyright>
		<Title>serviceadmin</Title>
		<OutputType>Exe</OutputType>
	</PropertyGroup>
	<Import Project="$(SolutionDir)Settings/MasterSettings.xml" />
	<ItemGroup>
		<ProjectReference Include="..\..\Mesh\Goedel.Mesh.Shell.ServiceAdmin\Goedel.Mesh.Shell.ServiceAdmin.csproj" />

	</ItemGroup>

</Project>
