<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<Product>Goedel.FSR</Product>
		<Description>Finite state recognizer support library.</Description>
		<Title>Goedel.FSR</Title>
		<Copyright>© 2020-2025 Threshold Secrets LLC</Copyright>
		<OutputType>Library</OutputType>
		<BuildPlatform>All</BuildPlatform>
	</PropertyGroup>

	<Import Project="$(SolutionDir)Settings/MasterSettings.xml" />

	<ItemGroup>
		<ProjectReference Include="..\Goedel.Utilities\Goedel.Utilities.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Exceptions.cs">
			<DependentUpon>Exceptions.exceptional</DependentUpon>
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<None Update="Exceptions.exceptional">
			<LastGenOutput>Exceptions.cs</LastGenOutput>
			<Generator>exceptional</Generator>
		</None>
	</ItemGroup>

</Project>
