#using System.Text
#using Goedel.Mesh
#using Goedel.Protocol
#using Goedel.Utilities
#using Goedel.Cryptography
#using Goedel.Cryptography.Dare
#% #pragma warning disable IDE0022
#% #pragma warning disable IDE0060
#% #pragma warning disable IDE1006
#xclass ExampleGenerator CreateExamples



#method MakeJSDeviceExamples CreateExamples Example
#% JSDevicePreparation(Example);
#% JSDeviceItself(Example);
#% JSDeviceOperations(Example);
#% JSDeviceMedia(Example);
#% JSDeviceNetwork(Example);
#% JSDeviceNetworkConfig(Example);
#% JSDeviceNetworkBoot(Example);
#end method




#zfile CreateExamples JSDevicePreparation "Examples\\JSDevicePreparation.md" Example
#% var jsdevice = Example.JSDevice.JsDevice;
#% var jsmodel = Example.JSDevice.JsModel;
~~~~
#% _Output.Write(jsmodel, Example.JSDevice.GeneralProperties);
~~~~
#end zfile


#zfile CreateExamples JSDeviceItself "Examples\\JSDeviceItself.md" Example
#% var jsdevice = Example.JSDevice.JsDevice;
#% var jsmodel = Example.JSDevice.JsModel;
~~~~
#% _Output.Write(jsdevice, Example.JSDevice.GeneralProperties);
~~~~
#end zfile


#zfile CreateExamples JSDeviceEarl "Examples\\JSDeviceEarl.md" Example
#% var jsdevice = Example.JSDevice;
~~~~
#{jsdevice.EARL}
~~~~
#end zfile


#zfile CreateExamples JSDeviceMedia "Examples\\JSDeviceMedia.md" Example
#% var jsdevice = Example.JSDevice.JsDevice;
~~~~
#% _Output.Write(jsdevice, Example.JSDevice.MediaProperties);
~~~~
#end zfile

#zfile CreateExamples JSDeviceOperations "Examples\\JSDeviceOperations.md" Example
#% var jsdevice = Example.JSDevice.JsDevice;
~~~~
#% _Output.Write(jsdevice, Example.JSDevice.OperationsProperties);
~~~~
#end zfile


#zfile CreateExamples JSDeviceNetworkBoot "Examples\\JSDeviceNetworkBoot.md" Example
#% var jsdevice = Example.JSDevice.JsDevice;
~~~~
#% _Output.Write(jsdevice, Example.JSDevice.NetworkProperties, FilterNetworkBootstrap);
~~~~
#end zfile

#zfile CreateExamples JSDeviceNetwork "Examples\\JSDeviceNetwork.md" Example
#% var jsdevice = Example.JSDevice.JsDevice;
~~~~
#% _Output.Write(jsdevice, Example.JSDevice.NetworkProperties, FilterNetworkService);
~~~~
#end zfile

#zfile CreateExamples JSDeviceNetworkConfig "Examples\\JSDeviceNetworkConfig.md" Example
#% var jsdevice = Example.JSDevice.JsDevice;
~~~~
#% _Output.Write(jsdevice, Example.JSDevice.NetworkProperties, FilterNetworkConfig);
~~~~
#end zfile




#end xclass
