#using System.Text
#using Goedel.Mesh
#using Goedel.Protocol
#using Goedel.Utilities
#using Goedel.Cryptography
#using Goedel.Cryptography.Dare
#% #pragma warning disable IDE0022
#% #pragma warning disable IDE0060
#% #pragma warning disable IDE1006
#xclass ExampleGenerator CreateExamples



#method MakeJSDeviceExamples CreateExamples Example
#% JSDeviceInitial(Example);
#end method

#zfile CreateExamples JSDeviceInitial "Examples\\JSDeviceInitial.md" Example
#% var jsdevice = Example.JSDevice;
~~~~

~~~~
#end zfile


#end xclass
