#using System.Text
#using Goedel.Mesh
#using Goedel.Protocol
#using Goedel.Utilities
#using Goedel.Cryptography
#using Goedel.Cryptography.Dare
#% #pragma warning disable IDE0022
#% #pragma warning disable IDE0060
#% #pragma warning disable IDE1006
#xclass ExampleGenerator CreateExamples



#method MakeJSContactExamples CreateExamples Example
#% JSContactSchema(Example);
#% JSContactKeys(Example);
#% JSContactJWK(Example);
#% JSContactEARL(Example);
#% JSContactDNS(Example);
#% JSContactGroups(Example);
#% JSContactUpdate(Example);
#% JSContactSMIME(Example);
#% JSContactOpenPGP(Example);
#% JSContactSSH(Example);
#% JSContactCode(Example);
#% JSContactCommit(Example);
#% JSContactComplete(Example);
#end method


#method WriteBytesHex byte[] data
#if (data != null)
#{data.ToStringBase16FormatHex()}
#else
$$$ Missing data $$$
#end if
#end method


#method2 CardExample string parent JsonObject example
{
    "@type":"Card",
    ...
    "#{parent}" : #!
#{JSONDebugWriter.Write(example, true, 2)},
    ...
    }
#end method2


#method3 CardExample string parent JsonObject example1 JsonObject example2
{
  "@type":"Card",
  ...
  "#{parent}" : #!
#{JSONDebugWriter.Write(example1, true, 2)},
  ...
#{JSONDebugWriter.Write(example2, true, 2)},
  ...
  }
~~~~
#end method3


#method StartCard bool ignore=true
~~~~
{
  "@type":"Card",
  ...
#end method

#method EndCard bool ignore=true
  }
~~~~
#end method

#zfile CreateExamples JSContactKeys "Examples\\JSContactKeys.md" Example
#% var jscontact = Example.JSContact;
#% // For example, Alice has many OpenPGP keys but only one that she uses with her email address alice@example.com
#% WriteTags (jscontact.Contact, ["email1", "emailKey", "emailKey1"]);
#end zfile


#zfile CreateExamples JSContactJWK "Examples\\JSContactJWK.md" Example
#% var jscontact = Example.JSContact;
#% WriteTags (jscontact.Contact, ["ssh1", "sshKey1"]);
#end zfile



#zfile CreateExamples JSContactGroups "Examples\\JSContactGroups.md" Example
#% var jscontact = Example.JSContact;
#% WriteTags (jscontact.Contact, ["group1", "email1", "git1", "ssh1"]);
#end zfile



#zfile CreateExamples JSContactUpdate "Examples\\JSContactUpdate.md" Example
#% var jscontact = Example.JSContact;
#% WriteTags (jscontact.Contact, ["update1", "updateKey1"]);
#end zfile







#zfile CreateExamples JSContactSchema "Examples\\JSContactSchema.md" Example
#% var jscontact = Example.JSContact;

#### Additional Card Properties

The following properties are added to the Card object specified in [RFC9553].

#% jscontact.AnnotatedSchema.DocumentProperties(_Output, "Card",[ "updates", "serviceGroups"],
#%        jscontact.Contact);

#### Extension to the EmailAddress Object

The EmailAddress object specified in [RFC9553] is extended to add the specified property.

#% jscontact.AnnotatedSchema.DocumentStructure(_Output, "EmailAddress", ["cryptoKeyIds"], 
#%      jscontact.EmailAddress, writeHeading: false);

#### Extension to the OnlineService Object

The OnlineService object specified in [RFC9553] is extended to add the specified property.

#% jscontact.AnnotatedSchema.DocumentStructure(_Output, "OnlineService", ["cryptoKeyIds"],
#%      jscontact.OnlineServiceWithKeys, writeHeading: false);

#### New Object JsonWebKeySet

The JsonWebKeySet object is added to the Card object with the following properties:

#% jscontact.AnnotatedSchema.DocumentStructure(_Output, "JsonWebKeySet", null, 
#%      jscontact.CryptoKeyWithJwk, writeHeading: false);;

#end zfile



#zfile CreateExamples JSContactComplete "Examples\\JSContactComplete.md" Example
#% var jscontact = Example.JSContact;
Alice's complete contact card is:

~~~~
{jscontact.CompleteContact}
~~~~
#end zfile





#zfile CreateExamples JSContactEARL "Examples\\JSContactEARL.md" Example
#% var jscontact = Example.JSContact;
#% var earl = Example.Earl;
~~~~
#{jscontact.EARL}
~~~~
#end zfile

#zfile CreateExamples JSContactDNS "Examples\\JSContactDNS.md" Example
#% var jscontact = Example.JSContact;
#% var earl = Example.Earl;
~~~~
_jscontact.#{CreateExamples.DnsHandleAlice} TXT "jscontact=#{jscontact.EARL}"
~~~~
#end zfile



#zfile CreateExamples JSContactSMIME "Examples\\JSContactSMIME.md" Example
#% var jscontact = Example.JSContact;
#% WriteTags (jscontact.Contact, ["emailKey3", "emailKey4"]);
#end zfile

#zfile CreateExamples JSContactOpenPGP "Examples\\JSContactOpenPGP.md" Example
#% var jscontact = Example.JSContact;
#% WriteTags (jscontact.Contact, ["emailKey1", "emailKey2"]);
#end zfile

#zfile CreateExamples JSContactSSH "Examples\\JSContactSSH.md" Example
#% var jscontact = Example.JSContact;
#% WriteTags (jscontact.Contact, ["ssh1", "sshKey1", "sshKey2", "sshKey3"]);
#end zfile

#zfile CreateExamples JSContactCommit "Examples\\JSContactCommit.md" Example
#% var jscontact = Example.JSContact;
#% WriteTags (jscontact.Contact, ["git1", "gitKey1"]);
#end zfile

#zfile CreateExamples JSContactCode "Examples\\JSContactCode.md" Example
#% var jscontact = Example.JSContact;
#% WriteTags (jscontact.Contact, ["code1", "code2","codeSign1", "codeSign2"]);
#end zfile


#method2 WriteTags JsContact contact List<string> include
#% StartCard ();
#% var trail = true;
#% WriteOut ("updates", contact.ServiceGroups, include, ref trail);
#% WriteOut ("serviceGroups", contact.ServiceGroups, include, ref trail, last:true);
#% WriteOut ("emails", contact.Emails, include, ref trail);
#% WriteOut ("onlineServices", contact.OnlineServices, include, ref trail);
#% WriteOut ("cryptoKeys", contact.CryptoKeys, include, ref trail, last:true);
#% EndCard ();
#end method2


#block
#% public void WriteOut<T> (string tag, Dictionary<string,T> entries, 
#%      List<string> include, ref bool trail, bool last=false) 
#%      where T : JsonObject {
#if (JsContactResults.IsEmpty (include, entries)) 
#! [Suppress #{tag}]
#if trail
    ...
#% trail = false;
#end if
#% return;
#end if
  "#{tag}" : {
#% var dots = true;
#foreach (var entry in entries) 
#if (JsContactResults.IsIncluded (include, entry.Key)) 
#% dots = true;
    "#{entry.Key}" : #!
#{JSONDebugWriter.Write(entry.Value, false, 3)}
#elseif (dots) 
#% dots = false;
    ...
#end if
#end foreach
#if last
    }
#else
    },
#end if
#% }
#end block





#method2 Write Dictionary<string,OnlineService> services bool part=false
{
    "@type":"Card",
    ...
    "onlineServices" : {#!
#% var sep = new Separator (",\n");
#foreach (var service in services)
#{sep}#!
"#{service.Key}" : #{JSONDebugWriter.Write(service.Value, false)}#!
#end foreach
#if (part) 

...
#end if
}
#end method2

#method2 Write Dictionary<string,CryptoKey> jsonKeys bool part=false
{
    "@type":"Card",
    ...
    "cryptoKeys" : {#!
#% var sep = new Separator  (",\n");
#foreach (var jsonKey in jsonKeys)
#{sep}#!
"#{jsonKey.Key}" : #{JSONDebugWriter.Write(jsonKey.Value, false)}#!
#end foreach
#if (part) 

...
#end if
}
#end method2





#method WriteEmails Dictionary<string,EmailAddress> jsonKeys
    "emails" : {
#% var sep = new Separator  (",\n");
#foreach (var jsonKey in jsonKeys)
#{sep}#!
      "#{jsonKey.Key}" : #{JSONDebugWriter.Write(jsonKey.Value, false,4)}#!
#end foreach
}
#end method


#method WriteUpdates Dictionary<string,Update> jsonKeys
    "updates" : {
#% var sep = new Separator  (",\n");
#foreach (var jsonKey in jsonKeys)
#{sep}#!
      "#{jsonKey.Key}" : #{JSONDebugWriter.Write(jsonKey.Value, false,4)}#!
#end foreach
}
#end method


#method WriteCryptoKeys Dictionary<string,CryptoKey> jsonKeys
    "cryptoKeys" : {
#% var sep = new Separator  (",\n");
#foreach (var jsonKey in jsonKeys)
#{sep}#!
      "#{jsonKey.Key}" : #{JSONDebugWriter.Write(jsonKey.Value, false,4)}#!
#end foreach
}
#end method


#end xclass
