#using System.Text
#using Goedel.Mesh
#using Goedel.Protocol
#using Goedel.Utilities
#using Goedel.Cryptography
#using Goedel.Cryptography.Dare
#% #pragma warning disable IDE0022
#% #pragma warning disable IDE0060
#% #pragma warning disable IDE1006
#xclass ExampleGenerator CreateExamples



#method MakeJSContactExamples CreateExamples Example
#% JSContactKeys(Example);
#% JSContactJWK(Example);
#% JSContactEARL(Example);
#% JSContactDNS(Example);
#% JSContactGroups(Example);
#% JSContactUpdate(Example);
#% JSContactSMIME(Example);
#% JSContactOpenPGP(Example);
#% JSContactSSH(Example);
#% JSContactCode(Example);
#% JSContactCommit(Example);
#end method

JSContactGroups


#method MakeEarlExamples CreateExamples Example
#% EarlExamples(Example);
#% EarlExamplesLocator(Example);
#% EarlExamplesName(Example);
#% Type0Envelope(Example);
#% Type0Meta(Example);
#% Type1Envelope(Example);
#% EarlKeyDerivation(Example);
#% Type0Nonce(Example);
#% EarlEncryption(Example);
#% EarlLocator(Example);
#% EarlAuthenticatedLocator(Example);
#% Unprotected(Example);
#% EarlManifest(Example);
#% SignedEnvelope25519(Example);
#% SignedEnvelope448(Example);
#end method


#method MakeDareExamples CreateExamples Example
#% MeshExamplesMessageMail(Example);
#% MeshExamplesMessageEDS(Example);
#% MeshExamplesMessageEncrypted(Example);
#% DareSchemaCatalog(Example);
#% DareSchemaSpool(Example);
#% ExamplesDAREMessage(Example);
#% MeshExamplesContainer(Example);
#end method


#method WriteBytesHex byte[] data
#if (data != null)
#{data.ToStringBase16FormatHex()}
#else
$$$ Missing data $$$
#end if
#end method


#zfile CreateExamples JSContactKeys "Examples\\JSContactKeys.md" Example
#% var jscontact = Example.JSContact;
#% // For example, Bob is trying to send an encrypted email to Alice, her 
#% //contact card lists two X.509v3 certificates but only one is an encryption 
#% // certificate with the JWK use parameter:
~~~~
#{JSONDebugWriter.Write(jscontact.EmailAddress)}
~~~~
#end zfile

#zfile CreateExamples JSContactJWK "Examples\\JSContactJWK.md" Example
#% var jscontact = Example.JSContact;
~~~~
#% Write(jscontact.JSContactSmime, true);
~~~~
#end zfile

#zfile CreateExamples JSContactEARL "Examples\\JSContactEARL.md" Example
#% var jscontact = Example.JSContact;
#% var earl = Example.Earl;
#{jscontact.EARL}
#end zfile

#zfile CreateExamples JSContactDNS "Examples\\JSContactDNS.md" Example
#% var jscontact = Example.JSContact;
#% var earl = Example.Earl;
~~~~
_jscontact.#{CreateExamples.DnsHandleAlice} TXT "jscontact=#{jscontact.EARL}"
~~~~
#end zfile

#zfile CreateExamples JSContactGroups "Examples\\JSContactGroups.md" Example
#% var jscontact = Example.JSContact;
~~~~
#{JSONDebugWriter.Write(jscontact.Group)}
~~~~

Each group identifier is specified as an online service:

~~~~
#% Write(jscontact.GroupMembers, true);
~~~~
#end zfile

#zfile CreateExamples JSContactUpdate "Examples\\JSContactUpdate.md" Example
#% var jscontact = Example.JSContact;
~~~~
#{JSONDebugWriter.Write(jscontact.Update)}

#% Write(jscontact.UpdateKeys);
~~~~
#end zfile

#zfile CreateExamples JSContactSMIME "Examples\\JSContactSMIME.md" Example
#% var jscontact = Example.JSContact;
~~~~
#% Write(jscontact.JSContactSmime, true);
~~~~
#end zfile

#zfile CreateExamples JSContactOpenPGP "Examples\\JSContactOpenPGP.md" Example
#% var jscontact = Example.JSContact;
~~~~
#% Write(jscontact.JSContactOpenpgp, true);
~~~~
#end zfile

#zfile CreateExamples JSContactSSH "Examples\\JSContactSSH.md" Example
#% var jscontact = Example.JSContact;
~~~~
#% Write(jscontact.Ssh);

#% Write(jscontact.SshKeys);
~~~~
#end zfile

#zfile CreateExamples JSContactCommit "Examples\\JSContactCommit.md" Example
#% var jscontact = Example.JSContact;
~~~~
#% Write(jscontact.Commit);

#% Write(jscontact.CommitKeys);
~~~~
#end zfile

#zfile CreateExamples JSContactCode "Examples\\JSContactCode.md" Example
#% var jscontact = Example.JSContact;
~~~~
#% Write(jscontact.CodeSign);

#% Write(jscontact.CodeSignKeys);
~~~~
#end zfile

#method2 Write Dictionary<string,OnlineService> services bool part=false
[#!
#% var sep = new Separator (",\n");
#foreach (var service in services)
#{sep}#!
"#{service.Key}" : #{JSONDebugWriter.Write(service.Value, false)}#!
#end foreach
#if (part) 

...
#end if
]
#end method2

#method2 Write Dictionary<string,Jwks> jsonKeys bool part=false
[#!
#% var sep = new Separator  (",\n");
#foreach (var jsonKey in jsonKeys)
#{sep}#!
"#{jsonKey.Key}" : #{JSONDebugWriter.Write(jsonKey.Value, false)}#!
#end foreach
#if (part) 

...
#end if
]
#end method2

#zfile CreateExamples EarlExamples "Examples\\EarlExamples.md" Example
#% var earl = Example.Earl;

~~~~
#{earl.EarlLocator}
#{earl.EarlName}
#{earl.EarlJSContact}
~~~~

All three forms refer to the exact same data object. The first two forms are URLs
that indicate that the corresponding ciphertext MAY be retreived via HTTPS at:

~~~~
#{earl.LocatorUri}
~~~~

#end zfile

#zfile CreateExamples EarlExamplesLocator "Examples\\EarlExamplesLocator.md" Example
#% var earl = Example.Earl;
~~~~
#{earl.EarlLocator}
~~~~
#end zfile

#zfile CreateExamples EarlExamplesName "Examples\\EarlExamplesName.md" Example
#% var earl = Example.Earl;
~~~~
#{earl.EarlName}
~~~~
#end zfile




#zfile CreateExamples Type0Envelope "Examples\\Type0Envelope.md" Example
#% var earl = Example.Earl;

For example, the payload:

~~~~
"#{Example.TestFile1Text}" =
#{earl.Payload.ToStringBase16FormatHex()}
~~~~

Is encoded as a Type 0 envelope without metadata by concatenating 

* ???

* The envelope type identifier (0), 

* a zero length byte to indicate an empty metadata field,

* a varint specifying the number of payload bytes (#{earl.Payload.Length}) followed by the payload bytes.

~~~~
#{earl.EnvelopeContent.ToStringBase16FormatHex()}
~~~~

#end zfile

#zfile CreateExamples Type0Meta "Examples\\Type0Meta.md" Example
#% var earl = Example.Earl;

The same payload as before MAY be enveloped with the following metadata:

~~~~
#{earl.ProtectedHeaderJson}
~~~~

The enveloped content is as before except that the metadata field is now specified:

~~~~
#{earl.BytesMeta.ToStringBase16FormatHex()}
~~~~

#end zfile


#zfile CreateExamples Type1Envelope "Examples\\Type1Envelope.md" Example
#% var earl = Example.Earl;
~~~~
"#{earl.FirstChunk}"
"#{earl.SecondChunk}"
~~~~

Is encoded as a Type 1 envelope by concatenating:

* ???

* The envelope type identifier (1), 

* a zero length byte to indicate an empty unprotected header field,

* a varint specifying the number of metadata bytes followed by the metadata,

* a varint specifying the number of bytes in the first chunk followed by the first chunk,

* a varint specifying the number of bytes in the second chunk followed by the second chunk,

* a zero length byte to indicate the end of the payload section,

* a zero length byte to indicate an empty trailer field.

~~~~
#{earl.BytesUnsigned.ToStringBase16FormatHex()}
~~~~

#end zfile



#zfile CreateExamples EarlKeyDerivation "Examples\\EarlKeyDerivation.md" Example
#% var earl = Example.Earl;


The content digest of the envelope shown in the first example is computed using SHAK256:

~~~~
#{earl.ContentDigest.ToStringBase16FormatHex()}
~~~~

The first byte of the result is set to the type identifier #{earl.VersionTag}, truncated
to the desired precision (#{earl.Precision} bits):

~~~~
#{earl.ContentDigestTruncated.ToStringBase16FormatHex()}
~~~~

The multipurpose key presentation is the result presented in Base32 with the characters 
grouped into sets of four with dashes:

~~~~
#{earl.EarlPath}
~~~~

Note that since there is an odd number of 20-bit segments in this example, only 
the upper half of the last byte is recorded in the key:

~~~~
#% var path = earl.EarlPath.FromBase32(partial: true);
#{path.ToStringBase16FormatHex()}
~~~~

The EARL forms consist of the scheme name, authority section (if specified) and the 
presentation form of the multi-purpose key:

~~~~
#{earl.EarlLocator}
#{earl.EarlName}
#{earl.EarlJSContact}
~~~~

#end zfile



#zfile CreateExamples Type0Nonce "Examples\\Type0Nonce.md" Example
#% var earl = Example.Earl;

If a different nonce is specified in the metadata:

~~~~
#{earl.ProtectedHeaderJson2}
~~~~

A different multi-purpose key is derived:

~~~~
#{earl.WithNonce.Uri}
~~~~

#end zfile



#zfile CreateExamples EarlEncryption "Examples\\EarlEncryption.md" Example
#% var earl = Example.Earl;

Since the encryption algorithm is AES-GCM with a 96 nonce and a 256 bit key,
it is necessary to generate 44 bytes to encrypt the enveloped data.

The key derrivation function, SHAKE-256 is applied to the multi-purpose key 
of the first example to obtain 44 bytes of output:

~~~~
#{earl.AesKeyNonce.ToStringBase16FormatHex()}
~~~~

The first 32 bytes of the result are the AES-GCM encryption key:

~~~~
encryption key =
#{earl.AesKeyNonce[0..32].ToStringBase16FormatHex()}
~~~~

The final 12 bytes of the result are the AES-GCM nonce:

~~~~
encryption nonce = 
#{earl.AesKeyNonce[32..].ToStringBase16FormatHex()}
~~~~

The enveloped plaintext data is encrypted under AES-GCM with the specified key and 
nonce to produce the ciphertext:

~~~~
ciphertext = 
#{earl.Ciphertext.ToStringBase16FormatHex()}
~~~~
#end zfile



#zfile CreateExamples EarlLocator "Examples\\EarlLocator.md" Example
#% var earl = Example.Earl;

The first locator value is computed from the multi-purpose key using the  
locator digest function, in this case SHA-3-256:

~~~~
locator1 =
#{earl.Locator1.ToStringBase16FormatHex()}
~~~~

The locator value is computed from the first locator value using the  
locator digest function, in this case SHA-3-256:

~~~~
locator =
#{earl.Locator1.ToStringBase16FormatHex()}
~~~~

The locator URI is a HTTPS well-known service in which the final element of the
path is the base64url encoded locator value.

~~~~
EARL =
#{earl.LocatorUri}
~~~~


#end zfile

#zfile CreateExamples EarlAuthenticatedLocator "Examples\\EarlAuthenticatedLocator.md" Example
#% var earl = Example.Earl;

~~~~
access authenticator =
#{earl.Password}
~~~~


#end zfile

#zfile CreateExamples Unprotected "Examples\\Unprotected.md" Example
#% var earl = Example.Earl;

~~~~
Unprotected Header =
#{earl.Signed25519.Header}
~~~~

#end zfile


#zfile CreateExamples EarlManifest "Examples\\EarlManifest.md" Example
#% var earl = Example.Earl;

~~~~
Metadata digest =
#{earl.Signed25519.MetadataDigest.ToStringBase16FormatHex()}

Payload digest =
#{earl.Signed25519.PayloadDigest.ToStringBase16FormatHex()}

Manifest =
#{earl.Signed25519.Manifest.ToStringBase16FormatHex()}
~~~~



#end zfile












#zfile CreateExamples SignedEnvelope25519 "Examples\\SignedEnvelope25519.md" Example
#% var earl = Example.Earl;

~~~~
Ed25519 private key =
#{(earl.SignatureEd25519 as KeyPairEd25519).PrivateKey.Secret.ToStringBase16FormatHex()}
~~~~

The trailer contains a Signatures property with a single entry specifying the key 
identifier of the signing key and the signature value:

~~~~
Trailer =
#{earl.Signed25519.Trailer}
~~~~

#end zfile


#zfile CreateExamples SignedEnvelope448 "Examples\\SignedEnvelope448.md" Example
#% var earl = Example.Earl;

The process for signing with an Ed448 key is identical except that achieving the
higher work factor requires use of a 512 bit digest:

~~~~
Unprotected Header =
#{earl.SignedEd448.Header}
~~~~

The private key used to generate the signature in this example is:

~~~~
Ed448 private key =
#{(earl.SignatureEd448 as KeyPairEd448).PrivateKey.Secret.ToStringBase16FormatHex()}
~~~~

The signature value is specified in the trailer as before:

~~~~
Trailer =
#{earl.SignedEd448.Trailer}
~~~~

#end zfile




#zfile CreateExamples DareSchemaCatalog "Examples\\DareSchemaCatalog.md" Example
#% Unfinished ("DareSchemaCatalog");
#end zfile

#zfile CreateExamples DareSchemaSpool "Examples\\DareSchemaSpool.md" Example
#% Unfinished ("DareSchemaSpool");
#end zfile

#zfile CreateExamples MeshExamplesContainer "Examples\\ExamplesContainer.md" Example
The data payloads in all the following examples are identical, only the
authentication and/or encryption is different. 

* Frame 0 is omitted in each case

* Frame 1..n consists of 300 bytes being the byte sequence 00, 01, 02, etc. 
repeating after 256 bytes.

For conciseness, the raw data format is omitted for examples after the first, except
where the data payload has been transformed, (i.e. encrypted).


####Simple sequence

The following example shows a simple sequence with first frame and a single data frame:

~~~~
#{Dare.ContainerFramingSimple}~~~~

Since there is no integrity check, there is no need for trailer entries.
The header values are:

#call DumpHeaders Dare.ContainerHeadersSimple


####Payload and chain digests

The following example shows a chain sequence with a first frame and three 
data frames. The headers of these frames is the same as before but the
frames now have trailers specifying the PayloadDigest and ChainDigest values:

#call DumpHeaders Dare.ContainerHeadersChain

####Merkle Tree

The following example shows a chain sequence with a first frame and six 
data frames. The trailers now contain the TreePosition and TreeDigest
values:

#call DumpHeaders Dare.ContainerHeadersMerkleTree

####Signed sequence

The following example shows a tree sequence with a signature in the final record.
The signing key parameters are:



~~~~
#{JSONDebugWriter.Write (Dare.SignatureAliceKey)}
~~~~

The sequence headers and trailers are:

#call DumpHeaders Dare.ContainerHeadersSigned

####Encrypted sequence

The following example shows a sequence in which all the frame payloads are encrypted 
under the same base seed established in a key agreement specified in the first frame.

#call DumpHeaders Dare.ContainerHeadersEncryptSingleSession

Here are the sequence bytes. Note that the content is now encrypted and has expanded by
25 bytes. These are the salt (16 bytes), the AES padding (4 bytes) and the 
JSON-B framing (5 bytes).

~~~~
#{Dare.ContainerFramingEncrypted}

~~~~


The following example shows a sequence in which all the frame payloads are encrypted 
under separate key agreements specified in the payload frames.

#call DumpHeaders Dare.ContainerHeadersEncryptIndependentSession

#end zfile


#method DumpHeaders List<SequenceFrame> Frames
#% if (Frames == null) {ReportMissing(); return;}
#foreach (var Frame in Frames)
#% DumpHeader (Frame);
#end foreach
#end method

#method DumpHeader SequenceFrame Frame
#% if (Frame == null) {ReportMissing(); return;}

Frame #{Frame.Header.SequenceInfo.Index}

~~~~
#{ JSONDebugWriter.Write (Frame.Header)}

#if (Frame.Trailer != null)
#{JSONDebugWriter.Write(Frame.Trailer)}
#else
[Empty trailer]
#end if
~~~~

#end method

#zfile CreateExamples MeshExamplesMessageMail "Examples\\ExamplesDAREMessageMail.md" Example

For example, consider the following mail message:

~~~~
#{Dare.MailMessageAsRFC822}~~~~

Existing encryption approaches require that header fields such as the subject line be encrypted 
with the body of the message or not encrypted at all. Neither approach is satisfactory.
In this example, the subject line gives away important information that the sender
probably assumed would be encrypted. But if the subject line is encrypted together with the
message body, a mail client must retrieve at least part of the message body to provide a 
'folder' view.

The plaintext form of the equivalent DARE Message encoding is:

~~~~
#{JSONDebugWriter.Write (Dare.MailMessageAsDAREPlaintext, false)}
~~~~

This contains the same information as before but the data we might wish to encrypt to
protect the confidentiality of the payload is separated from data required for 
processing.

#end zfile 

#zfile CreateExamples MeshExamplesMessageEDS "Examples\\ExamplesDAREMessageEDS.md" Example

The encoding of the 'From' header of the previous example as a plaintext EDS is as follows:

~~~~
#{Dare.EDSText}
~~~~
#end zfile

#zfile CreateExamples MeshExamplesMessageEncrypted "Examples\\MeshExamplesMessageEncrypted.md" Example

The following is an encrypted version of the message shown earlier. 
The payload and annotations have both increased in size as a result
of the block cipher padding. The header now
includes Recipients and Salt fields to enable the content to be decoded.

~~~~
#{JSONDebugWriter.Write (Dare.MailMessageAsDAREEncrypted, false)}
~~~~

For efficiency of processing, the ContentMetaData is presented in plaintext.
This header could be encrypted as an EDS sequence and presented as a 
cloaked header.

#end zfile


#zfile CreateExamples ExamplesDAREMessage "Examples\\ExamplesDAREMessage.md" Example

##Test Examples

In the following examples, Alice's encryption private key parameters are:

~~~~
#{JSONDebugWriter.Write (Dare.DareMessageAliceKey)}
~~~~

 Alice's signature private key parameters are:

~~~~
#{JSONDebugWriter.Write (Dare.SignatureAliceKey)}
~~~~

The body of the test message is the UTF8 representation of the following string:

~~~~
"#{Dare.DareMessageTest1.ToUTF8()}"
~~~~

The EDS sequences, are the UTF8 representation of the following strings:

~~~~
"#{Dare.DareMessageTest2.ToUTF8()}"
"#{Dare.DareMessageTest3.ToUTF8()}"
~~~~

#### Plaintext Message

A plaintext message without associated EDS sequences is an empty header
followed by the message body:

~~~~
#{JSONDebugWriter.Write (Dare.DAREMessageAtomic)}
~~~~

#### Plaintext Message with EDS

If a plaintext message contains EDS sequences, these are also in plaintext:

~~~~
#{JSONDebugWriter.Write (Dare.MessageAtomicDS)}
~~~~

#### Encrypted Message
#% var CryptoStackEncrypt = Dare.CryptoStackEncrypt;
#% var encHeader = Dare.MailMessageAsDAREEncrypted?.Header;
#% var Recipient = encHeader?.Recipients?[0] as Goedel.Test.Core.DareRecipientDebug;
#% var MessageEnc = Dare.MessageEnc;
#% var Salt = MessageEnc?.Header?.Salt;

The creator generates a base seed:

~~~~
#% WriteBytesHex (CryptoStackEncrypt?.BaseSeed);
~~~~

For each recipient of the message:

The creator generates an ephemeral key:

~~~~
#{JSONDebugWriter.Write (Recipient?.EphemeralPrivate)}
~~~~

The key agreement value is calculated:

~~~~
#% WriteBytesHex (Recipient?.KeyAgreement);
~~~~

The key agreement value is used as the input to a HKDF key
derivation function with the info parameter 
#{DareRecipient.KDFInfo.ToUTF8()} to create the key used to wrap the base seed:

~~~~
#% WriteBytesHex (Recipient?.EncryptionKey);
~~~~

The wrapped base seed is:

~~~~
#% WriteBytesHex (Recipient?.WrappedBaseSeed);
~~~~

This information is used to calculate the Recipient information
shown in the example below.

To encrypt a message, we first generate a unique salt value:


~~~~
#% WriteBytesHex (Salt);
~~~~

The base seed and salt value are used to generate the payload encryption
key:

~~~~
#% WriteBytesHex (CryptoStackEncrypt?.KeyEncrypt);
~~~~

Since AES is a block cipher, we also require an initializarion vector:

~~~~
#% WriteBytesHex (CryptoStackEncrypt?.IV);
~~~~

The output sequence is the encrypted bytes:

~~~~
#% WriteBytesHex (Dare.MessageEnc?.Body);
~~~~

Since the message is not signed, there is no need for a trailer.
The completed message is:

~~~~
#{JSONDebugWriter.Write (Dare.MessageEnc)}
~~~~

#### Signed Message

Signed messages specify the digest algorithm to be used in the header and
the signature value in the trailer. Note that the digest algorithm is not optional
since it serves as notice that a decoder should digest the payload value 
to enable signature verification.

~~~~
#{JSONDebugWriter.Write (Dare.DAREMessageAtomicSign)}
~~~~

#### Signed and Encrypted Message

A signed and encrypted message is encrypted and then signed.
The signer proves knowledge of the payload plaintext by providing the
plaintext witness value.

~~~~
#{JSONDebugWriter.Write (Dare.DAREMessageAtomicSignEncrypt)}
~~~~


#end zfile

#end xclass
