#using System.Text
#using Goedel.Mesh
#using Goedel.Protocol
#using Goedel.Utilities
#using Goedel.Cryptography
#using Goedel.Cryptography.Dare
#% #pragma warning disable IDE0022
#% #pragma warning disable IDE0060
#% #pragma warning disable IDE1006
#xclass ExampleGenerator CreateExamples



#method MakeJSDeviceExamples CreateExamples Example
#% JSDeviceInitial(Example);
#% JSDeviceEarl(Example);
#% JSDeviceNetwork(Example);
#% JSDeviceMedia(Example);
#% JSDeviceRelated(Example);
#% JSDeviceServices(Example);
#% JSDeviceMaint(Example);
#end method


#zfile CreateExamples JSDeviceEarl "Examples\\JSDeviceEarl.md" Example
#% var jsdevice = Example.JSDevice;
~~~~

~~~~
#end zfile

#zfile CreateExamples JSDeviceInitial "Examples\\JSDeviceInitial.md" Example
#% var jsdevice = Example.JSDevice;
~~~~

~~~~
#end zfile

#zfile CreateExamples JSDeviceNetwork "Examples\\JSDeviceNetwork.md" Example
#% var jsdevice = Example.JSDevice;
~~~~

~~~~
#end zfile

#zfile CreateExamples JSDeviceMedia "Examples\\JSDeviceMedia.md" Example
#% var jsdevice = Example.JSDevice;
~~~~

~~~~
#end zfile


#zfile CreateExamples JSDeviceRelated "Examples\\JSDeviceRelated.md" Example
#% var jsdevice = Example.JSDevice;
~~~~

~~~~
#end zfile


#zfile CreateExamples JSDeviceServices "Examples\\JSDeviceServices.md" Example
#% var jsdevice = Example.JSDevice;
~~~~

~~~~
#end zfile


#zfile CreateExamples JSDeviceMaint "Examples\\JSDeviceMaint.md" Example
#% var jsdevice = Example.JSDevice;
~~~~

~~~~
#end zfile





#end xclass
