<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<Product>Goedel.Cryptography.Nist</Product>
		<Description>Cryptographic support libraries.</Description>
		<Title>Goedel.Cryptography.Nist</Title>
		<Copyright>© 2020-2025 Threshold Secrets LLC</Copyright>
		<OutputType>Library</OutputType>
		<BuildPlatform>All</BuildPlatform>
	</PropertyGroup>

	<Import Project="$(SolutionDir)Settings/MasterSettings.xml" />
	<ItemGroup>
		<ProjectReference Include="..\Goedel.Utilities\Goedel.Utilities.csproj" />
		<ProjectReference Include="..\Goedel.Cryptography.Identifiers\Goedel.Cryptography.Identifiers.csproj" />
	</ItemGroup>
	
	
</Project>
