#region // Copyright - MIT License
//  © 2021 by Phill Hallam-Baker
//  
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//  
//  The above copyright notice and this permission notice shall be included in
//  all copies or substantial portions of the Software.
//  
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
//  THE SOFTWARE.
#endregion


using System.Net.Sockets;
using System.Security.Cryptography;

namespace Goedel.Protocol.Web;

/// <summary>
/// Encrypted token manager. This does not currently support key rotation or timestamping
/// of the tokens. This should be added when the cookie manager is migrated to this
/// library from Palimpsest.
/// </summary>
public class EncryptedTokenManager {

    ///<summary>The secret key. MUST be 16, 24 or 32 bytes.</summary> 
    public byte[] SecretKey { get; }

    ///<summary>The tag length in bytes, defaults to 16.</summary> 
    public int TagLength { get; init; } = 16;

    ///<summary>The nonce length in bytes, defaults to 12.</summary> 
    public int NonceLength { get; init; } = 12;

    /// <summary>
    /// Constructor, return a new instance.
    /// </summary>
    /// <param name="secretKey">Optionally specify the secret key. If null, the 
    /// <see cref="Platform.GetRandomBytes"/> delegate will be called to obtain one.</param>
    public EncryptedTokenManager (byte[]? secretKey =null) {
        SecretKey = secretKey ?? Platform.GetRandomBytes (32); 
        }

    /// <summary>
    /// Encrypt <paramref name="plaintext"/> with optional associated data <paramref name="associatedData"/>.
    /// To guard against nonce reuse and ensure each token is unique, the IV is generated by first 
    /// constructing the complete message with random data filling the IV slot and replaceing the
    /// IV slot with the digest of the message.
    /// <para>
    /// Ther order in which the data is presented is IV:Ciphertext:AssociatedData:Tag</para>
    /// </summary>
    /// <param name="plaintext">The data to encrypt.</param>
    /// <param name="associatedData">Optional associated data.</param>
    /// <returns></returns>
    public byte[] Encrypt(byte[] plaintext, byte[]? associatedData=null) {
        var length = NonceLength+ plaintext.Length + associatedData.LengthNullable() + TagLength;
        var result = new byte[length];

        // Construct a secure IV
        var preIv = Platform.GetRandomBytes(NonceLength);
        var nonce = Shake128.HashData(plaintext, NonceLength*2);
        Array.Copy(nonce, preIv, NonceLength);
        var iv = Shake128.HashData(preIv, NonceLength);

        var plaintextSpan = new ReadOnlySpan<byte>(plaintext);
        var nonceSpan = result.BufferAppendSpan(iv);

        var ciphertextSpan = new Span<byte>(result,NonceLength, plaintext.Length);
        var position = NonceLength+plaintext.Length;

        var associatedDataSpan = associatedData is null ? default :
                result.BufferAppendSpan(associatedData, position);
        position += associatedData.LengthNullable();

        var tagSpan = new Span<byte>(result, position, TagLength);

        var provider = new AesGcm(SecretKey, TagLength);
        provider.Encrypt(nonceSpan, plaintextSpan, ciphertextSpan, tagSpan, associatedDataSpan);

        return result;
        }

    /// <summary>
    /// Decrypt the encrypted package <paramref name="ciphertext"/> with 
    /// <paramref name="associatedDataLength"/> bytes of authenticated associated data.
    /// </summary>
    /// <param name="ciphertext">The encoded data package.</param>
    /// <param name="associatedDataLength">The associated data.</param>
    /// <returns></returns>
    public byte[] Decrypt(byte[]? ciphertext, int associatedDataLength = 0) {
        var plainTextLength = ciphertext.Length - NonceLength - TagLength - associatedDataLength;
        var result = new byte[plainTextLength];
        var plaintextSpan = new Span<byte>(result);

        var provider = new AesGcm(SecretKey, TagLength);

        var nonceSpan = new ReadOnlySpan<byte>(ciphertext, 0, NonceLength);
        var position = NonceLength;

        var ciphertextSpan = new ReadOnlySpan<byte>(ciphertext, position, plainTextLength);
        position += plainTextLength;

        var tagSpan = new ReadOnlySpan<byte>(ciphertext, position, TagLength);
        position += TagLength;

        var associatedDataSpan = new ReadOnlySpan<byte>(ciphertext, position, associatedDataLength);
        provider.Decrypt(nonceSpan, ciphertextSpan, tagSpan, plaintextSpan, associatedDataSpan);

        return result;
        }


    /// <summary>
    /// Encrypt the plaintext <paramref name="plaintext"/> with an appended date time stamp
    /// as associated data.
    /// </summary>
    /// <param name="plaintext">The data to encrypt.</param>
    /// <param name="dateTime">The time stamp to use. If the value default is specified, the
    /// current time is used.</param>
    /// <returns>The encrypted data package.</returns>
    public byte[] EncryptTimeStamped(byte[] plaintext, DateTime dateTime= default) {
        throw new NYI();
        
        }

    /// <summary>
    /// Decrypt the plaintext <paramref name="ciphertext"/> with an ap[pended date time stamp
    /// as associated data.
    /// </summary>
    /// <param name="ciphertext">The data to encrypt.</param>
    /// <param name="timeStamp">The timestamp.</param>
    /// <returns>The decrypted data package.</returns>
    public byte[] Decrypt(byte[] ciphertext, out DateTime timeStamp) {
        throw new NYI();

        }


    }
