<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<Product>Goedel.Discovery</Product>
		<Description>Service discovery.</Description>
		<Title>Goedel.Discovery</Title>
		<Copyright>© 2020-2025 Threshold Secrets LLC</Copyright>
		<OutputType>Library</OutputType>
		<BuildPlatform>All</BuildPlatform>
	</PropertyGroup>

	<Import Project="$(SolutionDir)Settings/MasterSettings.xml" />

	<ItemGroup>
		<ProjectReference Include="..\Goedel.Cryptography\Goedel.Cryptography.csproj" />
		<ProjectReference Include="..\Goedel.FSR\Goedel.FSR.csproj" />
		<ProjectReference Include="..\Goedel.Utilities\Goedel.Utilities.csproj" />
	</ItemGroup>
	<ItemGroup>
		<Compile Update="Exceptions.cs">
			<DependentUpon>Exceptions.exceptional</DependentUpon>
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
		</Compile>
		<Compile Update="ServiceAddressSplit.cs">
			<DependentUpon>ServiceAddressSplit.fsm</DependentUpon>
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<None Update="Exceptions.exceptional">
			<LastGenOutput>Exceptions.cs</LastGenOutput>
			<Generator>exceptional</Generator>
		</None>
		<None Update="ServiceAddressSplit.fsm">
			<LastGenOutput>ServiceAddressSplit.cs</LastGenOutput>
			<Generator>fsrcs</Generator>
		</None>
	</ItemGroup>

</Project>
