//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Goedel.Mesh.Shell {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Goedel.Mesh.Shell.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        internal static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Address.
        /// </summary>
        internal static string AccountAddress {
            get {
                return ResourceManager.GetString("AccountAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account UDF.
        /// </summary>
        internal static string AccountProfileUDF {
            get {
                return ResourceManager.GetString("AccountProfileUDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added device.
        /// </summary>
        internal static string AddedDevice {
            get {
                return ResourceManager.GetString("AddedDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device.
        /// </summary>
        internal static string Device {
            get {
                return ResourceManager.GetString("Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device UDF.
        /// </summary>
        internal static string DeviceProfileUDF {
            get {
                return ResourceManager.GetString("DeviceProfileUDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digest Algorithm.
        /// </summary>
        internal static string DigestAlgorithm {
            get {
                return ResourceManager.GetString("DigestAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encryption Algorithm.
        /// </summary>
        internal static string EncryptionAlgorithm {
            get {
                return ResourceManager.GetString("EncryptionAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envelope Id.
        /// </summary>
        internal static string EnvelopeId {
            get {
                return ResourceManager.GetString("EnvelopeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expires.
        /// </summary>
        internal static string Expires {
            get {
                return ResourceManager.GetString("Expires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group invitation.
        /// </summary>
        internal static string GroupInvitation {
            get {
                return ResourceManager.GetString("GroupInvitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        internal static string Host {
            get {
                return ResourceManager.GetString("Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host Address.
        /// </summary>
        internal static string HostAddress {
            get {
                return ResourceManager.GetString("HostAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Id.
        /// </summary>
        internal static string MessageId {
            get {
                return ResourceManager.GetString("MessageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a DARE Envelope.
        /// </summary>
        internal static string NotDareEnvelope {
            get {
                return ResourceManager.GetString("NotDareEnvelope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        internal static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payload Digest.
        /// </summary>
        internal static string PayloadDigest {
            get {
                return ResourceManager.GetString("PayloadDigest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN.
        /// </summary>
        internal static string PIN {
            get {
                return ResourceManager.GetString("PIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        internal static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string Recipient {
            get {
                return ResourceManager.GetString("Recipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Id.
        /// </summary>
        internal static string RequestId {
            get {
                return ResourceManager.GetString("RequestId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response Id.
        /// </summary>
        internal static string ResponseId {
            get {
                return ResourceManager.GetString("ResponseId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        internal static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string Sender {
            get {
                return ResourceManager.GetString("Sender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Address.
        /// </summary>
        internal static string ServiceAddress {
            get {
                return ResourceManager.GetString("ServiceAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service UDF.
        /// </summary>
        internal static string ServiceProfileUDF {
            get {
                return ResourceManager.GetString("ServiceProfileUDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        internal static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signer.
        /// </summary>
        internal static string Signer {
            get {
                return ResourceManager.GetString("Signer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start service.
        /// </summary>
        internal static string StartService {
            get {
                return ResourceManager.GetString("StartService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail.
        /// </summary>
        internal static string TransactionFail {
            get {
                return ResourceManager.GetString("TransactionFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string TransactionStart {
            get {
                return ResourceManager.GetString("TransactionStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string TransactionSuccess {
            get {
                return ResourceManager.GetString("TransactionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown-Command.
        /// </summary>
        internal static string UnknownCommand {
            get {
                return ResourceManager.GetString("UnknownCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URI.
        /// </summary>
        internal static string URI {
            get {
                return ResourceManager.GetString("URI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Witness.
        /// </summary>
        internal static string Witness {
            get {
                return ResourceManager.GetString("Witness", resourceCulture);
            }
        }
    }
}
