<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<Product>Goedel.Device</Product>
		<Description>Device Connection support libraries.</Description>
		<Title>Goedel.Device</Title>
		<Copyright>© 2025 Threshold Secrets LLC</Copyright>
		<OutputType>Library</OutputType>
		<BuildPlatform>All</BuildPlatform>
	</PropertyGroup>

	<Import Project="$(SolutionDir)Settings/MasterSettings.xml" />

	<ItemGroup>
		<ProjectReference Include="..\Goedel.Contacts\Goedel.Contacts.csproj" />
		<ProjectReference Include="..\Goedel.Cryptography.Dare\Goedel.Cryptography.Dare.csproj" />
		<ProjectReference Include="..\Goedel.Cryptography.Identifiers\Goedel.Cryptography.Identifiers.csproj" />
		<ProjectReference Include="..\Goedel.Cryptography\Goedel.Cryptography.csproj" />
		<ProjectReference Include="..\Goedel.IO\Goedel.IO.csproj" />
		<ProjectReference Include="..\Goedel.Protocol\Goedel.Protocol.csproj" />
		<ProjectReference Include="..\Goedel.Utilities\Goedel.Utilities.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="ConnectScehma.cs">
			<DependentUpon>ConnectScehma.Protocol</DependentUpon>
		  <DesignTime>True</DesignTime>
		  <AutoGen>True</AutoGen>
		</Compile>
		<Compile Update="Exceptions.cs">
			<DependentUpon>Exceptions.exceptional</DependentUpon>
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<None Update="ConnectScehma.Protocol">
		  <LastGenOutput>ConnectScehma.cs</LastGenOutput>
		  <Generator>PROTOGEN</Generator>
		</None>
		<None Update="Exceptions.Exceptional">
			<LastGenOutput>Exceptions.cs</LastGenOutput>
			<Generator>exceptional</Generator>
		</None>
	</ItemGroup>

</Project>
