//   Copyright © 2015 by Comodo Group Inc.
//  
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//  
//  The above copyright notice and this permission notice shall be included in
//  all copies or substantial portions of the Software.
//  
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
//  THE SOFTWARE.
//  
//  

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Goedel.Utilities;

namespace Goedel.Cryptography.Ticket {

    /// <summary>
    /// Cryptographic support operations
    /// </summary>
    public partial class Cryptography {

        /// <summary>
        /// Normalize PIN value by removing invalid characters. These are spaces, tabs,
        /// underscores and dashes.
        /// </summary>
        /// <param name="PIN">The original pin.</param>
        /// <returns>The normalized PIN.</returns>
        public static byte [] NormalizePIN(string PIN) {
            var StringBuilder = new StringBuilder();
            UTF8Encoding Encoder = new UTF8Encoding ();

            foreach (char c in PIN) {
                if (c != ' ' & c != '\t' & c != '\r' & c != '-' & c != '_') {
                    StringBuilder.Append (c);
                    }
                }

            return Encoder.GetBytes (StringBuilder.ToString());
            }

        /// <summary>
        /// Generate response to PIN challenge.
        /// </summary>
        /// <param name="PIN">The PIN value</param>
        /// <param name="ClientChallenge">Challenge generated by verifying party to be used as a key
        /// to the MAC</param>
        /// <param name="Authentication">MAC provider</param>
        /// <returns>The response to the PIN challenge.</returns>
        /// <exception cref="NYI">Not Yet Implemented</exception>
        public static byte[] GetPINKey(string PIN, byte[] ClientChallenge,
            Cryptography.Authentication Authentication) {

            byte [] NPIN = NormalizePIN (PIN);
            return Platform.HMAC_SHA2_512.Process(PIN, ClientChallenge);
            }

        /// <summary>
        /// Generate server side PIN authentication value
        /// </summary>
        /// <param name="PIN">Shared secret</param>
        /// <param name="ClientChallenge">Nonce generated by client.</param>
        /// <param name="Payload">Payload authenticated by PIN</param>
        /// <param name="Secret">Not used</param>
        /// <param name="Authentication">Message Authentication Code provider.</param>
        /// <returns></returns>
        public static byte[] ServerChallengeResponse (string PIN, byte [] ClientChallenge, 
                        string Payload, byte [] Secret, Cryptography.Authentication Authentication) {

            UTF8Encoding Encoder = new UTF8Encoding ();
            return ServerChallengeResponse (PIN, ClientChallenge, 
                        Encoder.GetBytes(Payload), Secret, Authentication);
            }

        /// <summary>
        /// Generate server side PIN authentication value
        /// </summary>
        /// <param name="PIN">Shared secret</param>
        /// <param name="ClientChallenge">Nonce generated by client.</param>
        /// <param name="Payload">Payload authenticated by PIN</param>
        /// <param name="Secret">Not used</param>
        /// <param name="Authentication">Message Authentication Code provider.</param>
        public static byte[] ServerChallengeResponse (string PIN, byte [] ClientChallenge, 
                        byte [] Payload, byte [] Secret,
                        Cryptography.Authentication Authentication) {

            var KPC = GetPINKey (PIN, ClientChallenge, Authentication);
            return Platform.HMAC_SHA2_512.Process(Payload, KPC);
            }

        /// <summary>
        /// Generate client side PIN authentication value
        /// </summary>
        /// <param name="PIN">Shared secret</param>
        /// <param name="ServerChallenge">Nonce generated by client.</param>
        /// <param name="Payload">Payload authenticated by PIN</param>
        /// <param name="Secret">Not used</param>
        /// <param name="Authentication">Message Authentication Code provider.</param>
        public static byte[] ClientChallengeResponse(string PIN, byte [] ServerChallenge, 
                    string Payload, byte [] Secret, Cryptography.Authentication Authentication) {
            UTF8Encoding Encoder = new UTF8Encoding ();
            return ClientChallengeResponse (PIN, ServerChallenge, 
                    Encoder.GetBytes(Payload), Secret, Authentication);
            }

        /// <summary>
        /// Generate client side PIN authentication value
        /// </summary>
        /// <param name="PIN">Shared secret</param>
        /// <param name="ServerChallenge">Nonce generated by client.</param>
        /// <param name="Payload">Payload authenticated by PIN</param>
        /// <param name="Secret">Not used</param>
        /// <param name="Authentication">Message Authentication Code provider.</param>
        public static byte[] ClientChallengeResponse(string PIN, byte [] ServerChallenge, 
                    byte [] Payload, byte [] Secret, Cryptography.Authentication Authentication) {

            var KPC = GetPINKey(PIN, ServerChallenge, Authentication);
            return Platform.HMAC_SHA2_512.Process(Payload, KPC);
            }
        }
    }
