<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<RootNamespace>Goedel.Acme</RootNamespace>
		<Product>Goedel.Acme</Product>
		<Title>Goedel.Acme</Title>
		<Description>ACME protocol library library.</Description>
		<Copyright>© 2020-2025 Threshold Secrets LLC</Copyright>
		<OutputType>Library</OutputType>
		<BuildPlatform>All</BuildPlatform>
	</PropertyGroup>

	<Import Project="$(SolutionDir)Settings/MasterSettings.xml" />

	<ItemGroup>
		<ProjectReference Include="..\..\Thing\Certes\Certes.csproj" />
		<ProjectReference Include="..\Goedel.Utilities\Goedel.Utilities.csproj" />
		<ProjectReference Include="..\..\Libraries\Goedel.Cryptography.Dare\Goedel.Cryptography.Dare.csproj" />
		<ProjectReference Include="..\..\Libraries\Goedel.Cryptography.Jose\Goedel.Cryptography.Jose.csproj" />
		<ProjectReference Include="..\..\Libraries\Goedel.Protocol.Service\Goedel.Protocol.Service.csproj" />
		<ProjectReference Include="..\..\Libraries\Goedel.Protocol\Goedel.Protocol.csproj" />
	</ItemGroup>
	<ItemGroup>
		<Compile Update="Exceptions.cs">
			<DependentUpon>Exceptions.exceptional</DependentUpon>
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
		</Compile>
	</ItemGroup>
	<ItemGroup>
		<None Update="Exceptions.exceptional">
			<LastGenOutput>Exceptions.cs</LastGenOutput>
			<Generator>exceptional</Generator>
		</None>
	</ItemGroup>
</Project>
